'use strict';

/**
 * Backend UI strings (F9.3e) — localized confirm-or-choose prefixes, the CONFIRM
 * summary, and the language instruction appended to LLM prompts so the assistant
 * replies in the user's selected language. English is the fallback.
 *
 * @module instances/flowdesk/interpreter/templates/ui-strings
 */

const UI_STRINGS = {
  en: { author: 'Author', approver: 'Approver', beneficiary: 'Request for', location: 'Location', user: 'User', correct: 'Correct?', review: 'Please review your "{title}" request:', submitPrompt: 'Submit it? (yes / edit)', langName: 'English', agent: {'outOfScope':'I can only help with HR and Finance service requests — separation, position and personal-data changes, dependency and household data, home leave and travel entitlements, recruitment, payroll and grants. Tell me what you need and I will raise the right request.','disambiguate':'I found a few services that might match — which one did you mean?','pickService':'Which service do you need?','ticketsHeader':'Here are your requests:','ticketsNone':'You have no requests matching that.','catalogRoot':'Here are the service categories I can help with — pick one to explore:','catalogCategory':'Here is what this category contains:','catalogPick':'Select a category or service','catalogBack':'← Back to all categories','catalogEmpty':'There are no services to show here.','ticketsError':'I could not retrieve your requests right now — please try again.','catalogError':'I could not load the service catalog right now.'},
    cancelConfirm: 'Do you want to cancel this request? Your draft will be kept so you can resume it. (yes / no)', skipRequired: 'I need this to complete the request, so I can\'t skip it — but you can provide it now or cancel.', didntCatch: 'Sorry, I didn\'t catch that.', capabilities: 'I can help you raise HR and Finance service requests — separation, position and personal-data changes, dependency and household data, home leave and travel entitlements, recruitment, payroll and grants. Let\'s continue.',
    optionsHint: 'Here are the available options:', skipOffer: 'This field is required to complete the request. You can provide it, park the request for later, or cancel. (provide / park / cancel)', handoffOffer: 'This is taking a few tries. Would you like me to hand you over to a human agent? (yes / no)', handoffDone: 'I\'ve passed your request to a human agent — reference {ref}. They\'ll follow up with you.', parked: 'No problem — I\'ve saved this request as a draft ({ref}). Just message me to pick up where we left off.', restartConfirm: 'Start over? I\'ll park the current request so nothing is lost. (yes / no)', capabilitiesList: 'Here\'s what I can help you request:', resumed: 'Let\'s continue where we left off.',
    switchConfirm: 'You have a "{current}" request in progress. Start a new "{next}" request instead? I\'ll keep the current one saved. (switch / continue)', resumeOffer: 'You have an unfinished "{title}" request from earlier. Would you like to continue it, or start something new? (resume / new)', submitted: 'Done — your request {ref} has been created. You can track it with that number.', internalError: 'Sorry — something went wrong on my side. Your request is safe; let us carry on.', directoryUnavailable: 'The employee directory is temporarily unavailable. You can try again, or type the name/email to enter it manually. (retry / type the name)', directoryManual: 'Please type the name and email to use.' },
  ru: { author: 'Автор заявки', approver: 'Согласующий', beneficiary: 'Заявка для', location: 'Локация', user: 'Пользователь', correct: 'Верно?', review: 'Проверьте заявку «{title}»:', submitPrompt: 'Оформить? (да / изменить)', langName: 'Russian', agent: {'outOfScope':'Я помогаю только с заявками по кадрам (HR) и финансам — увольнение, изменения должности и личных данных, иждивенцы, отпуск на родину и командировочные льготы, набор персонала, зарплата и гранты. Опишите, что вам нужно, и я оформлю нужную заявку.','disambiguate':'Я нашёл несколько подходящих услуг — какую вы имели в виду?','pickService':'Какая услуга вам нужна?','ticketsHeader':'Ваши заявки:','ticketsNone':'У вас нет заявок по этому запросу.','catalogRoot':'Вот категории услуг, с которыми я могу помочь — выберите одну:','catalogCategory':'Вот что содержит эта категория:','catalogPick':'Выберите категорию или услугу','catalogBack':'← Назад ко всем категориям','catalogEmpty':'Здесь нет услуг для показа.','ticketsError':'Не удалось получить ваши заявки — попробуйте ещё раз.','catalogError':'Не удалось загрузить каталог услуг.'},
    cancelConfirm: 'Отменить эту заявку? Черновик сохранится — вы сможете к нему вернуться. (да / нет)', skipRequired: 'Это поле нужно, чтобы оформить заявку, поэтому пропустить его нельзя — укажите значение или отмените заявку.', didntCatch: 'Извините, я не совсем понял.', capabilities: 'Я помогаю оформлять заявки по кадрам (HR) и финансам — оформление увольнения, изменение должности и личных данных, данные об иждивенцах, отпуск на родину и командировочные льготы, набор персонала, зарплата и гранты. Продолжим.',
    optionsHint: 'Доступные варианты:', skipOffer: 'Это поле обязательно для оформления заявки. Можно указать значение, отложить заявку или отменить. (указать / отложить / отменить)', handoffOffer: 'Не получается с нескольких попыток. Передать вас живому оператору? (да / нет)', handoffDone: 'Я передал вашу заявку живому оператору — номер {ref}. С вами свяжутся.', parked: 'Хорошо — я сохранил заявку как черновик ({ref}). Напишите мне, чтобы продолжить с того же места.', restartConfirm: 'Начать заново? Текущую заявку я отложу, ничего не потеряется. (да / нет)', capabilitiesList: 'Вот с чем я могу помочь:', resumed: 'Продолжим с того места, где остановились.',
    switchConfirm: 'У вас есть незавершённая заявка «{current}». Начать вместо неё новую заявку «{next}»? Текущую я сохраню. (переключить / продолжить)', resumeOffer: 'У вас есть незавершённая заявка «{title}». Продолжить её или начать новую? (продолжить / новая)', submitted: 'Готово — ваша заявка {ref} создана. Отслеживайте её по этому номеру.', internalError: 'Извините — у меня возникла внутренняя ошибка. Ваша заявка сохранена, продолжим.', directoryUnavailable: 'Справочник сотрудников временно недоступен. Можно попробовать снова или ввести имя/email вручную. (повторить / введите имя)', directoryManual: 'Введите имя и email.' },
  fr: { author: 'Auteur', approver: 'Approbateur', beneficiary: 'Demande pour', location: 'Lieu', user: 'Utilisateur', correct: 'Correct ?', review: 'Veuillez vérifier votre demande « {title} » :', submitPrompt: 'Soumettre ? (oui / modifier)', langName: 'French', agent: {'outOfScope':'Je peux seulement aider pour les demandes RH et Finances — cessation de service, changements de poste et de données personnelles, personnes à charge, congé dans les foyers et indemnités de voyage, recrutement, paie et subventions. Décrivez votre besoin et je créerai la bonne demande.','disambiguate':'J’ai trouvé plusieurs services possibles — lequel vouliez-vous dire ?','pickService':'De quel service avez-vous besoin ?','ticketsHeader':'Voici vos demandes :','ticketsNone':'Vous n’avez aucune demande correspondante.','catalogRoot':'Voici les catégories de services — choisissez-en une à explorer :','catalogCategory':'Voici le contenu de cette catégorie :','catalogPick':'Choisissez une catégorie ou un service','catalogBack':'← Retour aux catégories','catalogEmpty':'Aucun service à afficher ici.','ticketsError':'Je n’ai pas pu récupérer vos demandes — réessayez.','catalogError':'Je n’ai pas pu charger le catalogue des services.'},
    cancelConfirm: 'Voulez-vous annuler cette demande ? Votre brouillon sera conservé pour la reprendre. (oui / non)', skipRequired: 'J\'ai besoin de cette information pour compléter la demande ; je ne peux pas l\'ignorer — indiquez-la ou annulez.', didntCatch: 'Désolé, je n\'ai pas bien compris.', capabilities: 'Je peux vous aider à créer des demandes RH et Finances — cessation de service, changements de poste et de données personnelles, données des personnes à charge, congé dans les foyers et indemnités de voyage, recrutement, paie et subventions. Continuons.',
    optionsHint: 'Voici les options disponibles :', skipOffer: 'Ce champ est requis pour compléter la demande. Vous pouvez le fournir, mettre la demande en attente, ou annuler. (fournir / attente / annuler)', handoffOffer: 'Cela prend plusieurs essais. Souhaitez-vous que je vous transfère à un agent humain ? (oui / non)', handoffDone: 'J\'ai transmis votre demande à un agent humain — référence {ref}. Il vous recontactera.', parked: 'Pas de souci — j\'ai enregistré cette demande comme brouillon ({ref}). Écrivez-moi pour reprendre.', restartConfirm: 'Recommencer ? Je mettrai la demande actuelle en attente, rien ne sera perdu. (oui / non)', capabilitiesList: 'Voici ce que je peux vous aider à demander :', resumed: 'Reprenons là où nous nous étions arrêtés.',
    switchConfirm: 'Vous avez une demande « {current} » en cours. Démarrer plutôt une nouvelle demande « {next} » ? Je conserverai l\'actuelle. (changer / continuer)', resumeOffer: 'Vous avez une demande « {title} » inachevée. La continuer ou en commencer une nouvelle ? (reprendre / nouvelle)', submitted: 'Terminé — votre demande {ref} a été créée. Suivez-la avec ce numéro.', internalError: 'Désolé — une erreur interne est survenue. Votre demande est sauvegardée ; continuons.', directoryUnavailable: 'Le répertoire du personnel est temporairement indisponible. Réessayez, ou saisissez le nom / e-mail manuellement. (réessayer / saisir le nom)', directoryManual: 'Saisissez le nom et le-mail.' },
  es: { author: 'Autor', approver: 'Aprobador', beneficiary: 'Solicitud para', location: 'Ubicación', user: 'Usuario', correct: '¿Correcto?', review: 'Revise su solicitud «{title}»:', submitPrompt: '¿Enviar? (sí / editar)', langName: 'Spanish', agent: {'outOfScope':'Solo puedo ayudar con solicitudes de RR. HH. y Finanzas — separación, cambios de puesto y de datos personales, familiares a cargo, licencia para el país de origen y prestaciones de viaje, contratación, nómina y subvenciones. Describa lo que necesita y crearé la solicitud correcta.','disambiguate':'Encontré varios servicios posibles — ¿a cuál se refería?','pickService':'¿Qué servicio necesita?','ticketsHeader':'Estas son sus solicitudes:','ticketsNone':'No tiene solicitudes que coincidan.','catalogRoot':'Estas son las categorías de servicios — elija una para explorar:','catalogCategory':'Esto es lo que contiene esta categoría:','catalogPick':'Seleccione una categoría o servicio','catalogBack':'← Volver a las categorías','catalogEmpty':'No hay servicios para mostrar aquí.','ticketsError':'No pude recuperar sus solicitudes — inténtelo de nuevo.','catalogError':'No pude cargar el catálogo de servicios.'},
    cancelConfirm: '¿Desea cancelar esta solicitud? Se guardará el borrador para retomarlo. (sí / no)', skipRequired: 'Necesito este dato para completar la solicitud, así que no puedo omitirlo — indíquelo ahora o cancele.', didntCatch: 'Lo siento, no lo he entendido bien.', capabilities: 'Puedo ayudarle a crear solicitudes de RR. HH. y Finanzas — separación del servicio, cambios de puesto y de datos personales, datos de familiares a cargo, licencia para visitar el país de origen y prestaciones de viaje, contratación, nómina y subvenciones. Continuemos.',
    optionsHint: 'Estas son las opciones disponibles:', skipOffer: 'Este campo es obligatorio para completar la solicitud. Puede indicarlo, aparcar la solicitud o cancelar. (indicar / aparcar / cancelar)', handoffOffer: 'Esto está tomando varios intentos. ¿Desea que le transfiera a un agente humano? (sí / no)', handoffDone: 'He pasado su solicitud a un agente humano — referencia {ref}. Se pondrán en contacto con usted.', parked: 'Sin problema — he guardado esta solicitud como borrador ({ref}). Escríbame para continuar donde lo dejamos.', restartConfirm: '¿Empezar de nuevo? Aparcaré la solicitud actual para no perder nada. (sí / no)', capabilitiesList: 'Esto es en lo que puedo ayudarle:', resumed: 'Continuemos donde lo dejamos.',
    switchConfirm: 'Tiene una solicitud «{current}» en curso. ¿Iniciar en su lugar una nueva solicitud «{next}»? Guardaré la actual. (cambiar / continuar)', resumeOffer: 'Tiene una solicitud «{title}» sin terminar. ¿Continuarla o empezar una nueva? (retomar / nueva)', submitted: 'Listo — su solicitud {ref} ha sido creada. Puede seguirla con ese número.', internalError: 'Lo siento — ha ocurrido un error interno. Su solicitud está guardada; continuemos.', directoryUnavailable: 'El directorio de personal no está disponible temporalmente. Reintente o escriba el nombre/correo manualmente. (reintentar / escribir el nombre)', directoryManual: 'Escriba el nombre y el correo.' },
  ar: { author: 'مقدّم الطلب', approver: 'المُوافِق', beneficiary: 'الطلب لصالح', location: 'الموقع', user: 'المستخدم', correct: 'صحيح؟', review: 'يرجى مراجعة طلبك «{title}»:', submitPrompt: 'إرسال؟ (نعم / تعديل)', langName: 'Arabic', agent: {'outOfScope':'يمكنني المساعدة فقط في طلبات الموارد البشرية والشؤون المالية — إنهاء الخدمة، تغييرات الوظيفة والبيانات الشخصية، المُعالون، إجازة زيارة الوطن واستحقاقات السفر، التوظيف، الرواتب والمنح. صف ما تحتاجه وسأنشئ الطلب المناسب.','disambiguate':'وجدت عدة خدمات محتملة — أيها تقصد؟','pickService':'ما الخدمة التي تحتاجها؟','ticketsHeader':'إليك طلباتك:','ticketsNone':'لا توجد لديك طلبات مطابقة.','catalogRoot':'إليك فئات الخدمات التي يمكنني المساعدة بها — اختر واحدة:','catalogCategory':'إليك ما تحتويه هذه الفئة:','catalogPick':'اختر فئة أو خدمة','catalogBack':'← العودة إلى كل الفئات','catalogEmpty':'لا توجد خدمات لعرضها هنا.','ticketsError':'تعذر جلب طلباتك الآن — يرجى المحاولة مجددًا.','catalogError':'تعذر تحميل كتالوج الخدمات الآن.'},
    cancelConfirm: 'هل تريد إلغاء هذا الطلب؟ سيُحفَظ المسودة لتتمكن من متابعته لاحقًا. (نعم / لا)', skipRequired: 'أحتاج هذه المعلومة لإكمال الطلب، لذا لا يمكنني تخطيها — يرجى تقديمها الآن أو الإلغاء.', didntCatch: 'عذرًا، لم أفهم ذلك.', capabilities: 'يمكنني مساعدتك في إنشاء طلبات الموارد البشرية والشؤون المالية — إنهاء الخدمة، تغييرات الوظائف والبيانات الشخصية، بيانات المُعالين، إجازة زيارة الوطن واستحقاقات السفر، التوظيف، الرواتب والمنح. لنكمل.',
    optionsHint: 'إليك الخيارات المتاحة:', skipOffer: 'هذا الحقل مطلوب لإكمال الطلب. يمكنك تقديمه، أو إيقاف الطلب مؤقتًا، أو الإلغاء. (تقديم / إيقاف / إلغاء)', handoffOffer: 'يستغرق هذا عدة محاولات. هل تريد أن أحوّلك إلى موظف بشري؟ (نعم / لا)', handoffDone: 'لقد أحلت طلبك إلى موظف بشري — المرجع {ref}. سيتابعون معك.', parked: 'لا مشكلة — حفظت هذا الطلب كمسودة ({ref}). راسلني للمتابعة من حيث توقفنا.', restartConfirm: 'البدء من جديد؟ سأوقف الطلب الحالي مؤقتًا حتى لا يضيع شيء. (نعم / لا)', capabilitiesList: 'إليك ما يمكنني مساعدتك في طلبه:', resumed: 'لنكمل من حيث توقفنا.',
    switchConfirm: 'لديك طلب «{current}» قيد التنفيذ. هل تريد بدء طلب «{next}» جديد بدلاً منه؟ سأحتفظ بالطلب الحالي. (تبديل / متابعة)', resumeOffer: 'لديك طلب «{title}» غير مكتمل. هل تريد متابعته أم بدء طلب جديد؟ (متابعة / جديد)', submitted: 'تم — تم إنشاء طلبك {ref}. يمكنك تتبعه بهذا الرقم.', internalError: 'عذرًا — حدث خطأ داخلي. طلبك محفوظ؛ فلنكمل.', directoryUnavailable: 'دليل الموظفين غير متاح مؤقتًا. يمكنك إعادة المحاولة أو كتابة الاسم/البريد يدويًا. (إعادة / اكتب الاسم)', directoryManual: 'اكتب الاسم والبريد الإلكتروني.' },
  zh: { author: '申请人', approver: '审批人', beneficiary: '申请对象', location: '地点', user: '用户', correct: '正确吗？', review: '请检查您的“{title}”请求：', submitPrompt: '提交吗？（是 / 修改）', langName: 'Chinese', agent: {'outOfScope':'我只能协助人力资源和财务类请求——离职、职位与个人数据变更、受养人、探亲假与差旅福利、招聘、薪资和赠款。请描述您的需求，我会创建相应的请求。','disambiguate':'我找到了几个可能的服务——您指的是哪一个？','pickService':'您需要哪项服务？','ticketsHeader':'以下是您的请求：','ticketsNone':'没有符合条件的请求。','catalogRoot':'以下是我可以协助的服务类别——请选择一个查看：','catalogCategory':'此类别包含以下内容：','catalogPick':'选择一个类别或服务','catalogBack':'← 返回所有类别','catalogEmpty':'这里没有可显示的服务。','ticketsError':'暂时无法获取您的请求，请重试。','catalogError':'暂时无法加载服务目录。'},
    cancelConfirm: '要取消此请求吗？将保留草稿，方便您稍后继续。（是 / 否）', skipRequired: '完成请求需要此信息，因此无法跳过——请现在提供或取消。', didntCatch: '抱歉，我没有听清。', capabilities: '我可以帮助您提交人力资源和财务服务请求——离职、职位和个人数据变更、受养人数据、探亲假和差旅福利、招聘、薪资和赠款。我们继续吧。',
    optionsHint: '以下是可选项：', skipOffer: '完成请求需要此字段。您可以提供它、暂存请求，或取消。（提供 / 暂存 / 取消）', handoffOffer: '这已经尝试了几次。需要我为您转接人工客服吗？（是 / 否）', handoffDone: '我已将您的请求转给人工客服——编号 {ref}。他们会与您联系。', parked: '没问题——我已将此请求保存为草稿（{ref}）。给我留言即可从上次的位置继续。', restartConfirm: '重新开始吗？我会暂存当前请求，不会丢失任何内容。（是 / 否）', capabilitiesList: '我可以帮助您申请以下内容：', resumed: '让我们从上次的位置继续。',
    switchConfirm: '您有一个进行中的“{current}”请求。要改为开始新的“{next}”请求吗？我会保存当前请求。（切换 / 继续）', resumeOffer: '您有一个未完成的“{title}”请求。要继续它还是开始新的？（继续 / 新建）', submitted: '完成——已创建您的请求 {ref}。您可以用该编号跟踪。', internalError: '抱歉——我这边出现了内部错误。您的请求已保存；我们继续吧。', directoryUnavailable: '员工目录暂时不可用。您可以重试，或手动输入姓名/邮箱。（重试 / 输入姓名）', directoryManual: '请输入姓名和邮箱。' },
};

function ui(lang) { return UI_STRINGS[lang] || UI_STRINGS.en; }

/**
 * Instruction appended to LLM prompts so the model replies in the user's
 * SELECTED interface language — always, regardless of the language the user
 * happens to type in. The agent must never auto-switch languages.
 */
function langInstruction(lang) {
  const name = ui(lang).langName;
  return `\n\nAlways reply in ${name}, regardless of the language the user writes in. Never switch languages.`;
}

module.exports = { UI_STRINGS, ui, langInstruction };
