/**
 * AnomalyTaskMapper
 *
 * Maps extraction anomalies to iNeed task format.
 * Each anomaly type gets a structured title, description, and suggested actions.
 */

const ANOMALY_CONFIGS = {
  ORPHAN_RECORDS: {
    category: 'data-quality',
    priority: 'high',
    titleTemplate: 'Fix orphan records in {table}',
    descTemplate: 'Table {table} in {database} has {count} orphan records referencing non-existent parents via {fkColumn}. Impact: data integrity violation, potential application errors.',
    actions: ['Analyze root cause', 'Create data cleanup script', 'Add FK constraint', 'Update documentation'],
  },
  MISSING_FK: {
    category: 'schema-improvement',
    priority: 'medium',
    titleTemplate: 'Add missing FK: {table}.{column} → {targetTable}',
    descTemplate: 'Implicit foreign key detected in {database}: {table}.{column} → {targetTable}.{targetColumn} (confidence {confidence}%). No database constraint exists.',
    actions: ['Verify relationship', 'Check for orphans', 'Add FK constraint', 'Test application'],
  },
  DATA_INCONSISTENCY: {
    category: 'data-quality',
    priority: 'high',
    titleTemplate: 'Resolve data inconsistency in {table}',
    descTemplate: 'Data inconsistency found in {database}.{table}: {description}. Affected records: {count}.',
    actions: ['Root cause analysis', 'Define correct state', 'Create fix script', 'Add validation'],
  },
  UNEXPLAINED_TABLE: {
    category: 'documentation',
    priority: 'low',
    titleTemplate: 'Document purpose of table: {table}',
    descTemplate: 'Table {table} in {database} ({rowCount} rows, {columnCount} columns) could not be mapped to any business entity during extraction.',
    actions: ['Review with SME', 'Check code usage', 'Document or deprecate'],
  },
  COMPLEX_PROCEDURE: {
    category: 'technical-debt',
    priority: 'medium',
    titleTemplate: 'Review complex procedure: {procedureName}',
    descTemplate: 'Automatic analysis of {schema}.{procedureName} in {database} failed due to complexity. Error: {error}.',
    actions: ['Manual review', 'Extract business rules', 'Consider refactoring', 'Add documentation'],
  },
  LOW_COVERAGE: {
    category: 'knowledge-gap',
    priority: 'medium',
    titleTemplate: 'Improve extraction coverage for {database}',
    descTemplate: 'Database {database} extraction coverage is {coverage}% (target 80%). {gap}% of tables remain unmapped.',
    actions: ['SME review', 'Custom extraction rules', 'Mark technical tables', 'Re-extract'],
  },
};

class AnomalyTaskMapper {

  mapToTask(anomaly, context) {
    const config = ANOMALY_CONFIGS[anomaly.type];
    const vars = { ...anomaly, ...context, database: context.sourceDatabase, confidence: Math.round((anomaly.confidence || 0.5) * 100) };

    if (!config) {
      return {
        title: `Review anomaly: ${anomaly.type} in ${context.sourceDatabase}`,
        description: `Anomaly ${anomaly.type} (severity: ${anomaly.severity}) detected in ${context.sourceDatabase}. ${anomaly.description || ''}`,
        category: 'review',
        priority: anomaly.severity === 'high' ? 'high' : 'medium',
        suggestedActions: ['Review anomaly', 'Determine action', 'Document resolution'],
        metadata: this._buildMetadata(anomaly, context),
      };
    }

    return {
      title: this._interpolate(config.titleTemplate, vars),
      description: this._interpolate(config.descTemplate, vars),
      category: config.category,
      priority: config.priority,
      suggestedActions: config.actions,
      metadata: this._buildMetadata(anomaly, context),
    };
  }

  generateIneedText(task) {
    return [
      `Task: ${task.title}`,
      `Category: ${task.category} | Priority: ${task.priority}`,
      '',
      task.description,
      '',
      'Suggested Actions:',
      ...task.suggestedActions.map((a, i) => `${i + 1}. ${a}`),
      '',
      `Source: SQL Extraction | Database: ${task.metadata.database}`,
    ].join('\n');
  }

  mapAnomalies(anomalies, context) {
    return anomalies.map(a => this.mapToTask(a, context));
  }

  filterActionable(anomalies) {
    return anomalies.filter(a => !a.resolved && !a.hasTask && !(a.severity === 'low' && !['ORPHAN_RECORDS', 'DATA_INCONSISTENCY'].includes(a.type)));
  }

  _buildMetadata(anomaly, context) {
    return {
      sourceType: 'sql-extraction',
      anomalyType: anomaly.type,
      anomalyId: anomaly.id,
      sessionId: context.sessionId,
      database: context.sourceDatabase,
      severity: anomaly.severity,
      autoGenerated: true,
      generatedAt: new Date().toISOString(),
    };
  }

  _interpolate(template, vars) {
    return template.replace(/\{(\w+)\}/g, (_, key) => (vars[key] !== undefined ? vars[key] : `{${key}}`));
  }
}

module.exports = { AnomalyTaskMapper, anomalyTaskMapper: new AnomalyTaskMapper() };
