from .metrics import (
    PREDICTIONS_TOTAL,
    TRAINING_RUNS_TOTAL,
    PREDICTION_LATENCY,
    EMBEDDING_LATENCY,
    TRAINING_DURATION,
    MODEL_ACCURACY,
    CACHE_HIT_RATE,
    GRAPH_NODES_TOTAL,
    GRAPH_EDGES_TOTAL,
    track_prediction,
    track_embedding,
    update_model_metrics,
    update_graph_stats,
)
