'use strict';

const path = require('path');
const fs   = require('fs').promises;

const ARTEFACTS_DIR = path.join(__dirname, '../../../../Artefacts/codex-candidates');
const LOG = '[CodexCandidate]';

const PROMOTION_CRITERIA = {
  minActiveDays:  30,
  minSampleSize:  50,
  minConfidence:  0.9,
  minKqsImprovement: 0.1,
};

/**
 * CodexCandidateService — P6-004
 *
 * Inspects ACTIVE DerivedRules and generates Markdown Codex rule candidates
 * for human review and potential inclusion in the Codex rule set.
 */
class CodexCandidateService {

  /**
   * Find all ACTIVE rules that meet promotion criteria and generate candidates.
   * @param {Object} opts - Override default criteria
   * @returns {Promise<Array<{ruleId, filePath, content}>>}
   */
  async generateCandidates(opts = {}) {
    const criteria = { ...PROMOTION_CRITERIA, ...opts };
    const { ruleDerivationService } = require('./rule-derivation.service');

    const rules = await ruleDerivationService.getRules({ status: 'ACTIVE', limit: 200 });
    const cutoffDate = new Date(Date.now() - criteria.minActiveDays * 86400000).toISOString();

    const eligible = rules.filter(r =>
      r.activatedAt   && r.activatedAt < cutoffDate &&
      r.sampleSize    >= criteria.minSampleSize &&
      r.confidence    >= criteria.minConfidence &&
      r.kqsImprovement >= criteria.minKqsImprovement
    );

    if (eligible.length === 0) {
      console.log(`${LOG} No eligible rules for Codex promotion`);
      return [];
    }

    await fs.mkdir(ARTEFACTS_DIR, { recursive: true });

    const generated = [];
    for (const rule of eligible) {
      const content  = await this._renderMarkdown(rule);
      const filename = `EX-${rule.id.slice(0, 8)}.md`;
      const filePath = path.join(ARTEFACTS_DIR, filename);

      // Check if already generated (don't overwrite existing review)
      const exists = await fs.access(filePath).then(() => true).catch(() => false);
      if (exists) {
        console.log(`${LOG} Skipping ${filename} (already exists)`);
        continue;
      }

      await fs.writeFile(filePath, content, 'utf-8');
      generated.push({ ruleId: rule.id, filePath, filename });
      console.log(`${LOG} Generated ${filename}`);
    }

    console.log(`${LOG} Generated ${generated.length}/${eligible.length} new candidates`);
    return generated;
  }

  async _renderMarkdown(rule) {
    const methName = rule.recommendedMethodology?.name || rule.recommendsMethodologyId || 'Unknown';
    const docTypes = (rule.conditionDocTypes || []).join(', ') || 'ALL';
    const layers   = (rule.conditionLayers   || []).join(', ') || 'ALL';
    const activeDays = rule.activatedAt
      ? Math.floor((Date.now() - new Date(rule.activatedAt).getTime()) / 86400000)
      : null;

    return `# Codex Rule Candidate: EX-${rule.id.slice(0, 8)}

> Generated by RuleDerivationEngine on ${new Date().toISOString().slice(0, 10)}
> Source DerivedRule: \`${rule.id}\`

## Condition

- **Document Types:** ${docTypes}
- **Epistemic Layers:** ${layers}
- **Size Range:** any

## Recommendation

**Use Methodology:** \`${methName}\`

## Evidence

| Metric | Value |
|--------|-------|
| Sample Size | ${rule.sampleSize} documents |
| Confidence | ${(rule.confidence * 100).toFixed(1)}% |
| KQS with rule | ${rule.avgKqsWithRule?.toFixed(3) ?? 'N/A'} |
| KQS without rule | ${rule.avgKqsWithoutRule?.toFixed(3) ?? 'N/A'} |
| KQS Improvement | +${((rule.kqsImprovement || 0) * 100).toFixed(1)}% |
| Active Since | ${rule.activatedAt?.slice(0, 10) ?? 'N/A'} (${activeDays ?? '?'} days) |

## Suggested Codex Rule

\`\`\`
EX-XXX: For ${docTypes} documents at ${layers} epistemic layers,
apply ${methName} methodology.
Evidence: ${rule.sampleSize} documents, ${((rule.confidence || 0) * 100).toFixed(1)}% confidence,
+${((rule.kqsImprovement || 0) * 100).toFixed(1)}% KQS improvement.
\`\`\`

## Review Checklist

- [ ] Validate on held-out test set (not in training sample)
- [ ] Confirm no edge case regressions in adjacent document types
- [ ] Check methodology \`${methName}\` prompt templates are stable
- [ ] Approve for Codex inclusion

## Status

**Awaiting human review.** Approve by updating the Codex rule set with rule number EX-XXX.
`;
  }

  /** List already-generated candidate files */
  async listCandidates() {
    try {
      await fs.mkdir(ARTEFACTS_DIR, { recursive: true });
      const files = await fs.readdir(ARTEFACTS_DIR);
      return files.filter(f => f.endsWith('.md')).map(f => ({
        filename: f,
        filePath: path.join(ARTEFACTS_DIR, f),
      }));
    } catch {
      return [];
    }
  }
}

const codexCandidateService = new CodexCandidateService();
module.exports = { codexCandidateService, CodexCandidateService, PROMOTION_CRITERIA };
